name: CI Check
on: [push, pull_request]

jobs:
  test-490:
    name: Launch Openfire 4.9.0
    runs-on: ubuntu-24.04 # For newer curl version
    strategy:
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v4

      - name: Run Openfire
        uses: ./
        with:
          version: '4.9.0'
            
      - run: |
          set -e
          echo "Checking Openfire Admin Console"
          OPENFIRE_CONSOLE=$(curl -s -o /dev/null -I -w "%{http_code}^%header{Location}" http://127.0.0.1:9090/index.jsp)
          RESPONSE_CODE=$(echo $OPENFIRE_CONSOLE | cut -d^ -f1)
          LOCATION=$(echo $OPENFIRE_CONSOLE | cut -d^ -f2)
          if [ "$RESPONSE_CODE" != "302" ] | [ "$LOCATION" != 'http://127.0.0.1:9090/login.jsp?url=%2Findex.jsp' ]; then
            echo "Openfire Admin Console is not available"
            echo "Response code: $RESPONSE_CODE and Location: $LOCATION"
            exit 1
          else
            echo "Admin console up and redirecting to login page"
          fi
            
  test-483:
    name: Launch Openfire 4.8.3
    runs-on: ubuntu-24.04 # For newer curl version
    strategy:
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v4

      - name: Run Openfire
        uses: ./
        with:
          version: '4.8.3'
            
      - run: |
          set -e
          echo "Checking Openfire Admin Console"
          OPENFIRE_CONSOLE=$(curl -s -o /dev/null -I -w "%{http_code}^%header{Location}" http://127.0.0.1:9090/index.jsp)
          RESPONSE_CODE=$(echo $OPENFIRE_CONSOLE | cut -d^ -f1)
          LOCATION=$(echo $OPENFIRE_CONSOLE | cut -d^ -f2)
          if [ "$RESPONSE_CODE" != "302" ] | [ "$LOCATION" != 'http://127.0.0.1:9090/login.jsp?url=%2Findex.jsp' ]; then
            echo "Openfire Admin Console is not available"
            echo "Response code: $RESPONSE_CODE and Location: $LOCATION"
            exit 1
          else
            echo "Admin console up and redirecting to login page"
          fi

  test-daily:
    name: Launch Openfire Daily
    runs-on: ubuntu-24.04 # For newer curl version
    strategy:
      fail-fast: false
      
    steps:
      - uses: actions/checkout@v4

      - name: Run Openfire
        uses: ./
        with:
          daily: 'true'
            
      - run: |
          set -e
          echo "Checking Openfire Admin Console"
          OPENFIRE_CONSOLE=$(curl -s -o /dev/null -I -w "%{http_code}^%header{Location}" http://127.0.0.1:9090/index.jsp)
          RESPONSE_CODE=$(echo $OPENFIRE_CONSOLE | cut -d^ -f1)
          LOCATION=$(echo $OPENFIRE_CONSOLE | cut -d^ -f2)
          if [ "$RESPONSE_CODE" != "302" ] | [ "$LOCATION" != 'http://127.0.0.1:9090/login.jsp?url=%2Findex.jsp' ]; then
            echo "Openfire Admin Console is not available"
            echo "Response code: $RESPONSE_CODE and Location: $LOCATION"
            exit 1
          else
            echo "Admin console up and redirecting to login page"
          fi
            